### ISSUE TITLE
Release 1.0.0-beta as 1.0

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache-loader#4]
It looks like this branch has 3.x compatibility: https://github.com/canjs/can-stache-loader/tree/canjs3-webpack3

Here’s the beta release: https://github.com/canjs/can-stache-loader/releases/tag/v1.0.0-beta

I think we should release that beta as 1.0, so the next major release (2.0) has CanJS 4.x compatibility.

**Comment by cherifGsoul** [comment]
This branch https://github.com/canjs/can-stache-loader/tree/can5-webpack4 is tested with 5.X and webpack4 it has tests and demos.

**Comment by cherifGsoul** [comment]
Done!
